package com.byron.utils;

import com.badlogic.ashley.core.ComponentMapper;
import com.byron.components.AIComponent;
import com.byron.components.AgentComponent;
import com.byron.components.BodyComponent;
import com.byron.components.DestinationComponent;
import com.byron.components.HUDProgressBarComponent;
import com.byron.components.PositionComponent;
import com.byron.components.RenderComponent;
import com.byron.components.ShapeComponent;
import com.byron.components.SpeedComponent;
import com.byron.components.StatusComponent;
import com.byron.components.VelocityComponent;
import com.byron.components.WeaponComponent;
import com.byron.components.events.MilestoneEvent;
import com.byron.components.hud.ScoreEvent;
import com.byron.components.hud.TextComponent;
import com.byron.components.player.KeyboardComponent;
import com.byron.components.player.PlayerComponent;
import com.byron.components.player.WearComponent;
import com.byron.components.sprite.AnimableSpriteComponent;
import com.byron.components.sprite.SpriteComponent;
import com.byron.components.sprite.StackableSpriteComponent;
import com.byron.components.sprite.StackedSpritesComponent;
import com.byron.components.visuals.ColorInterpComponent;
import com.byron.components.visuals.LightComponent;
import com.byron.components.visuals.PositionInterpComponent;
import com.byron.components.visuals.RotationInterpComponent;
import com.byron.components.weapons.DamageComponent;
import com.byron.components.weapons.WeaponTag;

public class Mappers {

    public static final ComponentMapper<AgentComponent> agent = ComponentMapper.getFor(AgentComponent.class);
    public static final ComponentMapper<PositionComponent> position = ComponentMapper.getFor(PositionComponent.class);
    public static final ComponentMapper<RenderComponent> render = ComponentMapper.getFor(RenderComponent.class);
    public static final ComponentMapper<StatusComponent> status = ComponentMapper.getFor(StatusComponent.class);
    public static final ComponentMapper<KeyboardComponent> keyboard = ComponentMapper.getFor(KeyboardComponent.class);
    public static final ComponentMapper<BodyComponent> body = ComponentMapper.getFor(BodyComponent.class);
    public static final ComponentMapper<AnimableSpriteComponent> animableSprite = ComponentMapper.getFor(AnimableSpriteComponent.class);
    public static final ComponentMapper<StackedSpritesComponent> stackedSprites = ComponentMapper.getFor(StackedSpritesComponent.class);
    public static final ComponentMapper<VelocityComponent> velocity = ComponentMapper.getFor(VelocityComponent.class);
    public static final ComponentMapper<StackableSpriteComponent> stackableSprite = ComponentMapper.getFor(StackableSpriteComponent.class);
    public static final ComponentMapper<PlayerComponent> player = ComponentMapper.getFor(PlayerComponent.class);
    public static final ComponentMapper<WearComponent> wear = ComponentMapper.getFor(WearComponent.class);
    public static final ComponentMapper<ShapeComponent> shape = ComponentMapper.getFor(ShapeComponent.class);
    public static final ComponentMapper<LightComponent> light = ComponentMapper.getFor(LightComponent.class);
    public static final ComponentMapper<DestinationComponent> destination = ComponentMapper.getFor(DestinationComponent.class);
    public static final ComponentMapper<SpeedComponent> speed = ComponentMapper.getFor(SpeedComponent.class);
    public static final ComponentMapper<WeaponComponent> weapon = ComponentMapper.getFor(WeaponComponent.class);
    public static final ComponentMapper<AIComponent> ai = ComponentMapper.getFor(AIComponent.class);
    public static final ComponentMapper<HUDProgressBarComponent> progressBar = ComponentMapper.getFor(HUDProgressBarComponent.class);
    public static final ComponentMapper<TextComponent> text = ComponentMapper.getFor(TextComponent.class);
    public static final ComponentMapper<ScoreEvent> scoreEvent = ComponentMapper.getFor(ScoreEvent.class);
    public static final ComponentMapper<ColorInterpComponent> colorInterp = ComponentMapper.getFor(ColorInterpComponent.class);
    public static final ComponentMapper<PositionInterpComponent> positionInterp = ComponentMapper.getFor(PositionInterpComponent.class);
    public static final ComponentMapper<RotationInterpComponent> rotationInterp = ComponentMapper.getFor(RotationInterpComponent.class);
    public static final ComponentMapper<MilestoneEvent> milestone = ComponentMapper.getFor(MilestoneEvent.class);
    public static final ComponentMapper<WeaponTag> weaponTag = ComponentMapper.getFor(WeaponTag.class);
    public static final ComponentMapper<SpriteComponent> sprite = ComponentMapper.getFor(SpriteComponent.class);
    public static final ComponentMapper<DamageComponent> damage = ComponentMapper.getFor(DamageComponent.class);
}